AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - node_modules/**/*
    - Rakefile
    - features/**/*

# Configuration
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/ParameterLists:
  Enabled: false
Naming/PredicateName:
  NamePrefix:
    - is_
    - has_
    - have_
  ForbiddenPrefixes:
    - is_
    - has_
    - have_
Metrics/MethodLength:
  Max: 35
Metrics/ClassLength:
  Max: 350
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/**/*
    - spec/spec_helper.rb
Layout/SpaceBeforeFirstArg:
  Exclude:
    - config/application.rb
    - config/puma.rb
    - spec/spec_helper.rb
Style/BlockDelimiters:
  Exclude:
    - spec/**/* # multi-line {} okay with let
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DoubleNegation:
  Enabled: false



